### ISSUE TITLE
Autocomplete geeft foutmelding

### ISSUE THREAD

**Issue by camilleversteeg** [jeroenbos22/com.homewizard#12]
Uncaught TypeError: Cannot read property 'length' of null
    at autocomplete.js:1
    at XMLHttpRequest.i.onload (api.js:1)

Als ik een Homewizard component in de flow sleep en er begin in te typen opzoek naar een scene. 

Homey Firmware Version: 1.2.0-rc.9
Homewizard: v0.1.2

**Comment by jtebbens** [comment]
Bedankt voor je melding. Deze hebben we nog niet eerder gezien. Weet niet of er een relatie is met de nieuwe Homey Firmware versie 1.2.0-rc.9 aangezien ik deze zelf nog niet gebruik. We komen erop terug.

**Comment by camilleversteeg** [comment]
@jtebbens het grappige is dat de communicatie het nog wel doet met de Homewizard en dat oude gebouwde flows het nog doen. Alleen als ik het homewizard component in een flow sleep dan doet hij het niet meer. 

Als je wilt iets wilt debuggen via teamviewer, is dat mogelijk.

**Comment by jtebbens** [comment]
@camilleversteeg Bedankt, maar ik denk dat we nog even wachten met verder troubleshooten totdat 1.2.0rc9 stabiel is (nu nog steeds experimental). Ik lees nog aardig wat problemen met die versie. Ik ervaar persoonlijk namelijk helemaal geen problemen met 1.1.9 (huidige stable versie).

**Comment by spoelly** [comment]
1.2.0rc10 werken bestaande flows ook niet meer..
@jtebbens https://github.com/athombv/homey/issues/1430

**Comment by jeroenbos22** [comment]
Hey Spoelly, Can you try https://github.com/jeroenbos22/com.homewizard/tree/Firmware-1.2.0 to see if this fixes it?
