### ISSUE TITLE
Status Wijziging werkt niet

### ISSUE THREAD

**Issue by MarcIEMarc** [jeroenbos22/com.homewizard#19]
Hi Jeroen, 
Sinds enkele dagen mijn Homey gekoppeld aan de HomeWizard met behulp van jouw app. De verbinding tussen Homey en de Homewizard gaat niet goed. Voornamelijk als ik de status (Afwezig) wil wijzigen. Een enkele keer werkt het wel, maar meestal niet. Bij het uitvoeren van de Flow blijft het ringetje van het blokje "Activeer Preset" linksbovenin draaien en wordt uiteindelijk een rood uitroepteken (No Response). Vreemd genoeg blijven de thermometers wel correct werken. Enig idee waar dit aan kan liggen? Alvast bedankt voor je hulp. Grtn, Marc

**Comment by jeroenbos22** [comment]
Hey Marc,
Dit specifieke probleem nog nooit eerder gehoord. Lijkt alsof homey of homewizard een slechte / tijdelijk geen WiFi hebben. Status is een hele simpele call, zoals jij het probleem omschrijft lijkt homey geen response te krijgen van je homewizard. Enige wat ik daarin kan bedenken zijn netwerkproblemen.

Mvg jeroen

**Comment by MarcIEMarc** [comment]
Hi Jeroen, mijn homewizard doet wel vaker vreemd ja. Al eens een vast IP gegeven in het netwerk, maar dat mocht ook niet baten. Heb via Domoticz en RFXCom een omweg gevonden die de aan- en afwezigheid nu schakelt. Is het trouwens wel te verklaren dat de thermometers wel hun waarden blijven geven? Of die updaten maar de om de zoveel minuten en de Homey houdt die waarde vast?

Dank voor het snelle antwoorden.

Gr, Marc

**Comment by jtebbens** [comment]
Hoi,

Problemen met Homewizard wifi zijn bekend. Ik ervaar deze thuis soms 
ook. Wat soms wel helpt is 1 accesspoint alleen voor homewizard te 
gebruiken en geen andere verbindingen mee te maken.

Bijvoorbeeld een SSID die alleen voor homewizard gebruikt wordt en deze 
ook alleen maar B/G laat praten ipv mixed met N. Statisch IP is altijd 
aan te raden maar dat heb je al gedaan.

Wat betreft thermometers, klopt deze zit op een andere frequentie dan 
wifi natuurlijk zodoende dat die ongestoord signalen ontvangen maar ook 
dat is wel eens anders geweest.

Diverse forum kan je tweaks lezen van mensen die met de soldeerbout een 
16cm lang koperdraadje solderen op een van de voetjes van de 
434mhz/868mhz chip op ze een beter signaal te krijgen.

Ik weet niet welke thermometers je precies hebt maar die 868mhz werken 
altijd al beter dan de 434mhz versies en hebben ook een beter bereik. 
Mijn thermometer 868mhz staat op zolder en kan HW probleemloos beneden 
ontvangen.

Groet,

Jeroen

**Comment by MarcIEMarc** [comment]
Hi Jeroen,

Dat met een ander access point ga ik eens proberen. Bedankt voor de tip. Wat ik altijd vreemd gevonden heb is dat op momenten dat de Homewizard niet bereikbaar was via het lokale wifi netwerk, ik zonder problemen via "HomeWizard Online" er wel in kwam. Ook komen de pushberichten altijd door, ook als de HomeWizard lokaal niet te benaderen is. Heb jij misschien daar een verklaring voor? 

Grt,
Marc

**Comment by jeroenbos22** [comment]
Marc, 

Zou de antenne suggestie ook proberen, hier gedaan, mega verschil!

Ik sluit hierbij de issue aangezien het niet aan de app ligt.

Gr Jeroen

**Comment by MarcIEMarc** [comment]
Top! Dank beide Jeroen's, we gaan aan de knutsel hier :) Fijn weekend.
