### ISSUE TITLE
Homey krijgt geen gegevens van HW

### ISSUE THREAD

**Issue by Roy84** [jeroenbos22/com.homewizard#20]
Ik heb mijn homewizard aan de homey gekoppeld, ik krijg wel in mijn app de onderdelen te zien, maar geen info, zie ik iets over het hoofd of doe ik iets verkeerd?

Alvast bedankt!
![20180405_190912000_ios](https://user-images.githubusercontent.com/38114059/38388440-8c26a7ee-391b-11e8-86c9-c5a26532481c.png)

**Comment by Roy84** [comment]
Ik heb hem eraf gegooid en opnieuw geinstalleerd, nu krijg ik bij het invullen van het IP adres en wachtwoord een "ERROR: NO RESPONS" melding, dus nu moet ik eerst even zien dat ik er weer in kom, is dit een bekend probleem?

**Comment by Roy84** [comment]
Inmiddels heb ik de boel deels aan de gang, de verbinding is niet al te best met de homewizard, dat is ook een rede om over te stappen op de Homey, de 3 antenne's had ik vorig jaar al geplaatst, maar dat maakte niet veel verschil vondt ik zelf.

Nu kan ik inmiddels alles uitlezen, alleen de temperatuur instellen werkt niet meer, dat lukte begin van de avond wel, maar na een aantal keer de Homey opnieuw opstarten ( geen verbinding) lukte het niet meer, ik heb de heatlink verwijderd en opnieuw aangemeld, dat ging even goed.
Tot mijn vriendin de homewizard weer gebruikte om de verwarming iets hoger te zetten, en nu lukt het niet meer om het via de homey te doen, ook niet na ontkoppelen en opnieuw koppelen.

Hij blijft continu op 19 graden staan, ongeacht waar hij op de homewizard op staat.

**Comment by jtebbens** [comment]
Ik begrijp je frustratie maar probleem blijft een wifi probleem met 
Homewizard (en die herken ik hier thuis ook, heb namelijk 2 HW's).

De antenne's hebben alleen invloed op de 434 en 868mhz signalen die HW 
moet verwerken.

Verder zal de HW app op de homey met een vertraging (10 seconden) 
updates versturen naar de HW omdat we deze niet te veel willen pollen.

Vergeet ook niet dat Homewizard zelf afgelopen 2 weken nieuwe firmware 
updates heeft gedaan die de wifi instabiel maakte (veel uitval geweest 
bij mij thuis).


Groet,

Jeroen

**Comment by jeroenbos22** [comment]
Problem does not seem app-related
