### ISSUE TITLE
Missing functionality in the Homewizard App (e.g the Windmeter)

### ISSUE THREAD

**Issue by hlvdzande** [jeroenbos22/com.homewizard#21]
The Homewizard App does not support the Windmeter (among others thermostat, fire alarm).

**Comment by jtebbens** [comment]
I am already working on this not sure when ready for beta but it will come.

Kind regards / Groet,
Jeroen

Op 11 apr. 2018 om 10:35 heeft hlvdzande <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

The Homewizard App does not support the Windmeter (among others thermostat, fire alarm).

**Comment by PeetersJan** [comment]
"v0.1.6:

Added rainmeter
SIDENOTE just as the Energylink, heatlink etc you need to add Rain and windmeter separately. Verify homewizard has its windmeter units set to km/h else you get funny measures"

But windmeter can't be added!?

**Comment by hlvdzande** [comment]
Rainmeter was already operational. 
Still missing the Windmeter of the Homewizard Weatherstation, including:
- current wind speed
- wind gust
- wind direction
- wind chill
- wind speed max
- wind speed min

**Comment by hlvdzande** [comment]
Any progress on this????

**Comment by jtebbens** [comment]
Sorry for the delay due to private stuff. Windmeter has been added in beta release.

**Comment by hlvdzande** [comment]
Hai Jeroen,

No difference, I still can not select de windmeter while adding the device
Homewizard.

Regards, Henk.

Op za 22 dec. 2018 om 15:48 schreef jtebbens <notifications@github.com>:

**Comment by jeroenbos22** [comment]
Is added in latest beta, it was missing in the app.json. Beta branch is now in review for adding to appstore as beta.

**Comment by jtebbens** [comment]
Latest Beta merge has the new version and icon when you try to add it.

**Comment by hlvdzande** [comment]
Installed the homewizard Windmeter on the new Homey 2.0.0-rc.9 release.
The Windmeter part is now selectable, but no actual data is displayed on
the screen, only dashes "-"

Op za 22 dec. 2018 om 16:19 schreef jtebbens <notifications@github.com>:

**Comment by hlvdzande** [comment]
Geen data van de Windmeter`!!


[image: image.png]

Op wo 11 apr. 2018 om 11:38 schreef jtebbens <notifications@github.com>:
