### ISSUE TITLE
koppeling met homey mislukt

### ISSUE THREAD

**Issue by bobmijwaard** [jeroenbos22/com.homewizard#22]
Ik probeer mijn homewizard te koppelen met de homey en moet ip adres en password opgeven maar krijg direct daarna de melding error: no response (binnen 1 seconde) wat doe ik verkeerd. De homewizard heeft een static IP.

Bob

**Comment by jtebbens** [comment]
Hallo Bob,

Dit moet gewoon werken. Let op dat je het wachtwoord gebruikt die je voor directe communicatie gebruikt van je homewizard app en niet je homewizard online wachtwoord.

Kind regards / Groet,
Jeroen

Op 19 mei 2018 om 21:03 heeft bobmijwaard <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Ik probeer mijn homewizard te koppelen met de homey en moet ip adres en password opgeven maar krijg direct daarna de melding error: no response (binnen 1 seconde) wat doe ik verkeerd. De homewizard heeft een static IP.

Bob

**Comment by bobmijwaard** [comment]
die typefout lag aan mij hoor, maar resultaat blijft hetzelfde

**Comment by jtebbens** [comment]
Dan is je wachtwoord onjuist.
Anders zal een pasword recovery moeten uitvoern van homizard via de usb kabel en laptop of computer.

Kind regards / Groet,
Jeroen

Op 19 mei 2018 om 21:29 heeft bobmijwaard <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

die typefout lag aan mij hoor, maar resultaat blijft hetzelfde

**Comment by jeroenbos22** [comment]
Seems like incorrect password
