### ISSUE TITLE
send 'gas stand' 

### ISSUE THREAD

**Issue by seekelen** [jeroenbos22/com.homewizard#24]
I want to send my 'gas stand' to mindergas.nl via the homey app of mindergas.nl. I can't find a way to do this with a 'if-card' of the energy-link.

Can you make this possible?

**Comment by jeroenbos22** [comment]
@jeroentebbens Is gas stand a public tag yet?

**Comment by jeroenbos22** [comment]
Tag seems to be available, you should be able to use that for what you want.

**Comment by jtebbens** [comment]
![image](https://user-images.githubusercontent.com/18558267/50376041-780a7600-0607-11e9-94ec-72c46b3df32d.png)
