### ISSUE TITLE
Kan app niet installeren op Homey 2.0 rc3

### ISSUE THREAD

**Issue by rzandbergen** [jeroenbos22/com.homewizard#25]
Bij het installeren van de app krijg ik de volgende foutmelding: **Invalid driver class: appliances: [object Object]**

Homey firmware: 2.0.0-rc.3

**Comment by jeroenbos22** [comment]
Should be fixed using latest beta branch, is in appstore for review now

**Comment by rzandbergen** [comment]
I am now be able to install the app, thanks.

Op 22 dec. 2018 om 16:03 heeft Jeroen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Should be fixed using latest beta branch, is in appstore for review now
