### ISSUE TITLE
Windmeter

### ISSUE THREAD

**Issue by hvhol** [jeroenbos22/com.homewizard#29]
The windmeter in Homewizard is working fine, but in Homey I got no readings at all ?
![photo_2019-01-15_12-27-31](https://user-images.githubusercontent.com/25131976/51177809-feda0800-18c0-11e9-80fd-0b55f022b3e7.jpg)

**Comment by WollyA** [comment]
Same problem for me and also for a friend. All other HomeWizard stuff is running fine, just the windmeter has no values.

**Comment by jtebbens** [comment]
FIxed....try this version to test https://github.com/jtebbens/com.homewizard

**Comment by hvhol** [comment]
I've got it working again i can chose the homewizard by Ip adres Thermometer, Rain everything is working perfect but still no readings van the windmeter

**Comment by jtebbens** [comment]
Could you sent me your /get-sensors from your homey device so I can check why the code fails? 

Verstuurd vanaf mijn iPhone

Op 16 mrt. 2019 om 12:57 heeft hvhol <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

I've got it working again i can chose the homewizard by Ip adres Thermometer, Rain everything is working perfect but still no readings van the windmeter

**Comment by hvhol** [comment]
Hoi Jeroen , 
Waar vind ik mijn get codes?

Groet 
Henk

Verstuurd vanaf mijn iPhone

**Comment by jtebbens** [comment]
Dat doe je in je browser

HTTP://x.x.x.x <HTTP://x.x.x.x> /<wachtwoord homewizard>/get-sensors

Verstuurd vanaf mijn iPhone

Op 16 mrt. 2019 om 12:57 heeft hvhol <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

I've got it working again i can chose the homewizard by Ip adres Thermometer, Rain everything is working perfect but still no readings van the windmeter

**Comment by hvhol** [comment]
Hoi Jeroen ,
Dank voor je snelle reactie , ik krijg het volgende te zien:

{"status": "ok", "version": "3.403", "request": {"route": "/get-sensors" }, "response": {"preset":0,"time":"2019-03-16 15:00","switches":[],"uvmeters":[],"windmeters":[{"id":5,"name":"Wind tuin","code":"11985446","model":1,"lowBattery":"no","version":2.31,"unit":0,"ws":14.3,"dir":"ENE 67","gu":12.3,"wc":10.3,"te":10.3,"ws+":18.5,"ws+t":"12:17","ws-":10.7,"ws-t":"11:12","favorite":"no"}],"rainmeters":[{"id":4,"name":"Regen tuin","model":0,"mm":0.0,"3h":0.0,"favorite":"no"}],"thermometers":[{"id":0,"name":"Tuin","channel":1,"model":0,"te":11.2,"hu":73,"te+":11.2,"te+t":"14:57","te-":9.6,"te-t":"10:59","hu+":92,"hu+t":"10:59","hu-":73,"hu-t":"14:52","outside":"yes","favorite":"no"},{"id":1,"name":"Woonkamer","channel":2,"model":0,"te":19.5,"hu":59,"te+":19.5,"te+t":"14:48","te-":19.1,"te-t":"12:27","hu+":59,"hu+t":"10:59","hu-":59,"hu-t":"10:59","outside":"no","favorite":"no"},{"id":2,"name":"Slaapkamer","channel":3,"model":0,"te":17.5,"hu":62,"te+":17.5,"te+t":"14:57","te-":16.3,"te-t":"11:01","hu+":62,"hu+t":"12:35","hu-":58,"hu-t":"11:01","outside":"no","favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [], "heatlinks": [], "hues": [], "scenes": [], "kakusensors": [], "cameras": []}}



Is dit wat je bedoelt ?

 

Groet,

Henk

 

Van: jtebbens <notifications@github.com> 
Verzonden: zaterdag 16 maart 2019 13:55
Aan: jeroenbos22/com.homewizard <com.homewizard@noreply.github.com>
CC: hvhol <hvhol@me.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter (#29)

 

Dat doe je in je browser

HTTP://x.x.x.x <HTTP://x.x.x.x> /<wachtwoord homewizard>/get-sensors

Verstuurd vanaf mijn iPhone

Op 16 mrt. 2019 om 12:57 heeft hvhol <notifications@github.com  <mailto:notifications@github.com%20%3cmailto:notifications@github.com> <mailto:notifications@github.com> > het volgende geschreven:

I've got it working again i can chose the homewizard by Ip adres Thermometer, Rain everything is working perfect but still no readings van the windmeter

**Comment by jtebbens** [comment]
Bedankt ik ga kijken voor je wat er fout gaat dan.

Kind regards / Groet,
Jeroen

Op 16 mrt. 2019 om 15:01 heeft hvhol <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Hoi Jeroen ,
Dank voor je snelle reactie , ik krijg het volgende te zien:

{"status": "ok", "version": "3.403", "request": {"route": "/get-sensors" }, "response": {"preset":0,"time":"2019-03-16 15:00","switches":[],"uvmeters":[],"windmeters":[{"id":5,"name":"Wind tuin","code":"11985446","model":1,"lowBattery":"no","version":2.31,"unit":0,"ws":14.3,"dir":"ENE 67","gu":12.3,"wc":10.3,"te":10.3,"ws+":18.5,"ws+t":"12:17","ws-":10.7,"ws-t":"11:12","favorite":"no"}],"rainmeters":[{"id":4,"name":"Regen tuin","model":0,"mm":0.0,"3h":0.0,"favorite":"no"}],"thermometers":[{"id":0,"name":"Tuin","channel":1,"model":0,"te":11.2,"hu":73,"te+":11.2,"te+t":"14:57","te-":9.6,"te-t":"10:59","hu+":92,"hu+t":"10:59","hu-":73,"hu-t":"14:52","outside":"yes","favorite":"no"},{"id":1,"name":"Woonkamer","channel":2,"model":0,"te":19.5,"hu":59,"te+":19.5,"te+t":"14:48","te-":19.1,"te-t":"12:27","hu+":59,"hu+t":"10:59","hu-":59,"hu-t":"10:59","outside":"no","favorite":"no"},{"id":2,"name":"Slaapkamer","channel":3,"model":0,"te":17.5,"hu":62,"te+":17.5,"te+t":"14:57","te-":16.3,"te-t":"11:01","hu+":62,"hu+t":"12:35","hu-":58,"hu-t":"11:01","outside":"no","favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [], "heatlinks": [], "hues": [], "scenes": [], "kakusensors": [], "cameras": []}}



Is dit wat je bedoelt ?

 

Groet,

Henk

 

Van: jtebbens <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: zaterdag 16 maart 2019 13:55
Aan: jeroenbos22/com.homewizard <com.homewizard@noreply.github.com <mailto:com.homewizard@noreply.github.com> >
CC: hvhol <hvhol@me.com <mailto:hvhol@me.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter (#29)

 

Dat doe je in je browser

HTTP://x.x.x.x <HTTP://x.x.x.x> <HTTP://x.x.x.x <HTTP://x.x.x.x> > /<wachtwoord homewizard>/get-sensors

Verstuurd vanaf mijn iPhone

Op 16 mrt. 2019 om 12:57 heeft hvhol <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> %20%3cmailto:notifications@github.com <mailto:notifications@github.com> > <mailto:notifications@github.com <mailto:notifications@github.com> > > het volgende geschreven:

I've got it working again i can chose the homewizard by Ip adres Thermometer, Rain everything is working perfect but still no readings van the windmeter

**Comment by jeroenbos22** [comment]
Fixed in current version (0.2.1), is now pending as beta app in Athoms appstore

**Comment by jeroenbos22** [comment]
Please try the latest beta for windmeter fix https://apps.athom.com/app/com.homewizard. Please let us know if you ran into any problem or if the app works fine.
