### ISSUE TITLE
Can't connect to Homewizard anymore

### ISSUE THREAD

**Issue by jjongen** [jeroenbos22/com.homewizard#30]
Since I have disconnected to my Hormewizard it seems that I can't connect to it anymore.
Here some background info first.

I use Homewizard for years but Homey is in my possession now for 1 week. I installed the Homewizard app to be able to use info from it. The setuo went great but when I noticed that I couldn't reach my Homewizard I disconnected it (I don'y know anymore what I exactly did but I believe I Disabled the App.

I connected all my devices to Homey but noticed that my Temp sensors where to far from my Homey but Homewizard had no issue with the distance (I have modded the antenna). So I wanted to connect the Temperature sensors (433 Mhz) through my Homewizard. But when I select ADD DEVICE => HOMEWIZARD => THERMOMETER I can't choose one. I gives me 2 empty pull down menu's and when I open 1 the Homey Apps freezes and closes.

I have Installed the app again, rebooted Homey etc. But when I Reinstall it I am not getting the option again to inset the IP addess and password as if Homey already has it. 

Now I am clueless what to do.

I hope someone can help me with this.

With Kind regards

Joep Jongen (ps the answer can be in dutch)

**Comment by jeroenbos22** [comment]
It sounds like the Ip address of your HW changed, you can give it a fixed ip in your router. You should be able to change it. If not try removing / re-adding the HW but like I said it should be editable.
