### ISSUE TITLE
Windmeter does not work

### ISSUE THREAD

**Issue by hlvdzande** [jeroenbos22/com.homewizard#31]
New added windmeter does nit work. No windmeter data is displayed in the app.

**Comment by jtebbens** [comment]
We are aware of this issue.
Personal life currently holds me back fixing it (baby boy born). When free time permits I try to resolve it.

Verstuurd vanaf mijn iPhone

Op 3 feb. 2019 om 11:04 heeft hlvdzande <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

New added windmeter does nit work. No windmeter data is displayed in the app.

**Comment by jtebbens** [comment]
FIxed, try this version to test https://github.com/jtebbens/com.homewizard

**Comment by hlvdzande** [comment]
Jeroen,

Ik heb versie 0.2.0 draaien. Daar werkt eigenlijk niets correct: regenmeter
niet, temperatuur meters niet en de windmeter heeft nog nooit gewerkt. Jouw
link verwijst naar versie 1.9

Waar vind ik nu de correct app??

Groeten. Henk.



Op vr 15 mrt. 2019 17:20 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
https://github.com/jtebbens/com.homewizard
Even met cli installeren

Verstuurd vanaf mijn iPhone

Op 15 mrt. 2019 om 19:36 heeft hlvdzande <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Jeroen,

Ik heb versie 0.2.0 draaien. Daar werkt eigenlijk niets correct: regenmeter
niet, temperatuur meters niet en de windmeter heeft nog nooit gewerkt. Jouw
link verwijst naar versie 1.9

Waar vind ik nu de correct app??

Groeten. Henk.



Op vr 15 mrt. 2019 17:20 schreef jtebbens <notifications@github.com <mailto:notifications@github.com> >:

**Comment by PetervdK65** [comment]
Kan deze alleen via CLI worden geïnstalleerd? Of wordt de app in de store nog ge-update?

**Comment by hlvdzande** [comment]
Node.js installatie loopt stuk na inloggen.
Een nieuwe app zou wel welkom zijn. Ik wacht al een jaar op een compleet
werkende versie.




Op za 30 mrt. 2019 12:02 schreef PetervdK65 <notifications@github.com>:

**Comment by jeroenbos22** [comment]
Updated version is now in the master branch. Submitted this as beta version to Athom's appstore, it's now awaiting approval. Enjoy! Thanx @jtebbens for the fixes

**Comment by jeroenbos22** [comment]
Please try the latest beta for windmeter fix https://apps.athom.com/app/com.homewizard. Please let us know if you ran into any problem or if the app works fine.

**Comment by hlvdzande** [comment]
I did. It works fine, fantastic!

Thanx Jeroen.

Cheers Henk.

Op ma 1 apr. 2019 om 22:22 schreef Jeroen <notifications@github.com>:

**Comment by PetervdK65** [comment]
Thanks. Alas not able to do it at this time, will try it when i have hooked up my  spare Homey later today.

Keep u posted.

 

Regards, Peter

**Comment by hlvdzande** [comment]
Te vroeg gejuigt.
App displayed de actuele waarden niet meer??!!

Hierbij de dump:

e76c02ee-752b-4dfe-87eb-716717422fc7

Op ma 1 apr. 2019 22:22 schreef Jeroen <notifications@github.com>:

**Comment by PetervdK65** [comment]
Heb vanmorgen de beta op de andere Homey gezet en tot nu toe werkt hij bij mij al een paar uur prima.

Waardes worden nog steeds ge-update.

 

Grt, Peter

**Comment by jtebbens** [comment]
Ok bedankt Peter.

Dan denk ik dat er lokaal wellicht nog iets mis gaat bij Henk. :(

Het is voor mij lastig testen omdat ik geen windmeter/weather station 
thuis heb dus moet uitgaan van de exports die wij krijgen om te testen 
en die zijn statisch.

Mvg,

Jeroen

**Comment by hlvdzande** [comment]
Jeroen,

Niet alleen de windmeter haakt af. Alle thermometers, rainmeter ook.
Het lijkt erop dat je app ineerns niet meer om nieuwe informatie vraagt.
Kun je ook mooi zien bij Insights, alle grafieken worden flatliners
_________ :-(


Groeten, Henk.

---------------------

Op wo 3 apr. 2019 om 15:09 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
Dan denk ik dat je HW een ander ip adres heeft gekregen tussen door waarop de Homey homewizard zijn connectie kwijt is.

Verstuurd vanaf mijn iPhone

**Comment by hlvdzande** [comment]
Denk  het niet. Homewizard draait met een vast ip adres (192.168.1.52)
Gezet tijdens initiële setup, jaren geleden


Op wo 3 apr. 2019 15:45 schreef jtebbens <notifications@github.com>:

**Comment by PetervdK65** [comment]
Gaat hier nu ook fout zie ik. Ik dacht even al mijn thermo’s toe te voegen, maar nu gaat er iets fout.

Van 2 thermo’s krijg ik alleen de HUM en niet te TMP (dacht dat dat wel vanzelf goed zou komen), maar nu wordt geen enkele waarde meer ververst.

Alle waardes zijn het laatst tussen 35 minuten en 1 uur ververst.

Na het herstarten van Homey verandert er niets, na het herstarten van de HomeWizard app staan de niet gevulde waardes op “a few seconds ago” maar worden niet ververst.

 

Heb net alle thermo’s en de windmeter verwijderd en opnieuw toegevoegd. Weer een paar zonder temp. Verwijderen en opnieuw aanmaken en dan werkt het wel.

Nu staat alles weer up-2-date. Ik zal het de komende uren even in de gaten houden.

 

Grt, Peter

**Comment by PetervdK65** [comment]
So far so good, het werkt nu prima sinds 17:45. Alle thermometers en de windmeter blijven updaten.

Ik heb wel de temperature monitor  app uitgezet. Gebruik jij die ook Henk?

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: woensdag 3 april 2019 17:23
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

Gaat hier nu ook fout zie ik. Ik dacht even al mijn thermo’s toe te voegen, maar nu gaat er iets fout.

Van 2 thermo’s krijg ik alleen de HUM en niet te TMP (dacht dat dat wel vanzelf goed zou komen), maar nu wordt geen enkele waarde meer ververst.

Alle waardes zijn het laatst tussen 35 minuten en 1 uur ververst.

Na het herstarten van Homey verandert er niets, na het herstarten van de HomeWizard app staan de niet gevulde waardes op “a few seconds ago” maar worden niet ververst.

 

Heb net alle thermo’s en de windmeter verwijderd en opnieuw toegevoegd. Weer een paar zonder temp. Verwijderen en opnieuw aanmaken en dan werkt het wel.

Nu staat alles weer up-2-date. Ik zal het de komende uren even in de gaten houden.

 

Grt, Peter

**Comment by hlvdzande** [comment]
Nee, ken ik niet.

Op wo 3 apr. 2019 21:29 schreef PetervdK65 <notifications@github.com>:

**Comment by PetervdK65** [comment]
Op dit moment verversen alle sensoren nog steeds.

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: woensdag 3 april 2019 21:30
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

So far so good, het werkt nu prima sinds 17:45. Alle thermometers en de windmeter blijven updaten.

Ik heb wel de temperature monitor  app uitgezet. Gebruik jij die ook Henk?

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: woensdag 3 april 2019 17:23
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

Gaat hier nu ook fout zie ik. Ik dacht even al mijn thermo’s toe te voegen, maar nu gaat er iets fout.

Van 2 thermo’s krijg ik alleen de HUM en niet te TMP (dacht dat dat wel vanzelf goed zou komen), maar nu wordt geen enkele waarde meer ververst.

Alle waardes zijn het laatst tussen 35 minuten en 1 uur ververst.

Na het herstarten van Homey verandert er niets, na het herstarten van de HomeWizard app staan de niet gevulde waardes op “a few seconds ago” maar worden niet ververst.

 

Heb net alle thermo’s en de windmeter verwijderd en opnieuw toegevoegd. Weer een paar zonder temp. Verwijderen en opnieuw aanmaken en dan werkt het wel.

Nu staat alles weer up-2-date. Ik zal het de komende uren even in de gaten houden.

 

Grt, Peter

**Comment by PetervdK65** [comment]
En op dit moment nog steeds zonder problemen.

Ik ga er dus van uit dat het met de update zelf wel goed zit.

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: donderdag 4 april 2019 08:08
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

Op dit moment verversen alle sensoren nog steeds.

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: woensdag 3 april 2019 21:30
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

So far so good, het werkt nu prima sinds 17:45. Alle thermometers en de windmeter blijven updaten.

Ik heb wel de temperature monitor  app uitgezet. Gebruik jij die ook Henk?

 

From: Peter [mailto:petervdk65@ziggo.nl] 
Sent: woensdag 3 april 2019 17:23
To: 'jeroenbos22/com.homewizard'; 'jeroenbos22/com.homewizard'
Cc: 'Comment'
Subject: RE: [jeroenbos22/com.homewizard] Windmeter does not work (#31)

 

Gaat hier nu ook fout zie ik. Ik dacht even al mijn thermo’s toe te voegen, maar nu gaat er iets fout.

Van 2 thermo’s krijg ik alleen de HUM en niet te TMP (dacht dat dat wel vanzelf goed zou komen), maar nu wordt geen enkele waarde meer ververst.

Alle waardes zijn het laatst tussen 35 minuten en 1 uur ververst.

Na het herstarten van Homey verandert er niets, na het herstarten van de HomeWizard app staan de niet gevulde waardes op “a few seconds ago” maar worden niet ververst.

 

Heb net alle thermo’s en de windmeter verwijderd en opnieuw toegevoegd. Weer een paar zonder temp. Verwijderen en opnieuw aanmaken en dan werkt het wel.

Nu staat alles weer up-2-date. Ik zal het de komende uren even in de gaten houden.

 

Grt, Peter

**Comment by hlvdzande** [comment]
Hoe gaat het hier?


Weinig tijd gehad, druk aan het klussen, volgende week komt de nieuwe
keuken. Is ook gelijk de oorzaak van de problemen.


Als de stroom eraf gaat en er later weer opgezet wordt, gaat het mis. Alle
Homewizard devices laten flatlines zien. Komen ook niet meer bij. Oplossing:

Homewizard App herstarten

Alle devices eerst verwijderen en dan weer toevoegen!

Dan werkt het weer.

Alle andere apps (bv Hue, Toon, etc) kunnen daar wel tegen. Nadat de stroom
hersteld is, werken de apps en devices vanzelf weer normaal.

Is wel iets voor de volgende update/versie van de Homewizard App


Inhoudelijk:

Bij de Windmeter;

echt- en gevoelstemperatuur zijn identiek

Bij Homewizard zelf kun je alleen de gevoelstemp zien.

Temp-echt kan wat mij betreft weg


Bij de thermometer(s)

Homewizard levert ook nog de volgende data mee bij een thermometer:

Min Temperatuur @tijdstip

Max Temperatuur @tijdstip

Min Luchtvochtigheid @tijdstip

Max Luchtvochtigheid @tijdstip

zou leuk zijn als die ook gedisplayed werden!


@Peter, thermometer monitor gebruikte ik niet. Even naar gekeken, grappig
dat de app alle thermometers van zelf vindt!

Zag wel dat ie de windmeter temperatuur niet weer geeft (Jeroen?).


Sinds de laatste power down, werkt alles correct :-)


Groeten, Henk.

Op wo 3 apr. 2019 om 21:29 schreef PetervdK65 <notifications@github.com>:
