### ISSUE TITLE
Invited smartlock

### ISSUE THREAD

**Issue by Midi170** [jeroenbos22/com.homewizard#32]
Hallo toppers,
Ik heb hier ook een homewizard staan. Met onder andere aantal schakelaar,  heatlink en een invited smartlock. Ben aan het overwegen om een Homey aan te schaffen. Maar mijn vraag is werkt mijn invted smartlock nog via die app homewizard voor Homey?

Alvast bedankt.
MVG, Michel

**Comment by jeroenbos22** [comment]
Michel,

Nog niet, deze hebben we nog niet toegevoegd.

Heb je al gekeken of deze door homey zelf ondersteund word op apps.athom.com
?
Mvg

Jeroen




Op vr 1 mrt. 2019 om 00:46 schreef Midi170 <notifications@github.com>

**Comment by jeroenbos22** [comment]
Is this still wanted?

**Comment by telenut** [comment]
Ja, ik heb hetzelfde probleem...

**Comment by telenut** [comment]
Graag ja, is enige reden dat ik hem niet inwisselde
