### ISSUE TITLE
App werkt niet meer na update Homey 2.1.1-rc1

### ISSUE THREAD

**Issue by xs2rene** [jeroenbos22/com.homewizard#34]
Hi,
Na Homey update (4 dagen geleden) naar 211rc1 werkt de temperatuur sensoren en heatlink niet meer.
Temperatuur op alle Homewizard sensoren is al 4 dagen hetzelfde
Ook geen verbetering na update naar 0.21 beta app
90c86805-bf8a-435d-ad58-dfdee7d3b4ab
grtz
René

**Comment by jtebbens** [comment]
Hallo René,

Homey Firmware 2.1.1 is net uit. Ik heb deze net ge-update en zal kijken wat mijn Heatlink en thermometers doen.

Verstuurd vanaf mijn iPhone

**Comment by xs2rene** [comment]
Hi Jeroen,
Gisterenavond Homey geupdate naar 2.1.1 en daarna homewizard uit en aan gezet, helaas nog steeds geen communicatie tussen deze 2.
grtz

**Comment by xs2rene** [comment]
Hi Jeroen,
Opgelost; ipadres homewizard was gewijzigd; alles doet het weer.
Grtz
