### ISSUE TITLE
Homewizard doet het niet meer na installatie beta

### ISSUE THREAD

**Issue by Itsmmai** [jeroenbos22/com.homewizard#35]
Hallo Jeroen,

Vanavond heb ik de HomeWizard app gedeïnstalleerd en de beta geïnstalleerd. Daarna kon ik nergens meer het IP en de poort van de homewizard ingeven. Hierdoor ook geen apparaten meer selecteren. Nu heb ik de beta weer verwijderd en de originele weer geïnstalleerd maar heb ik hetzelfde.

Wat doe ik fout ?

Groet,
Ab

**Comment by jtebbens** [comment]
Hallo Abel,

Na de installatie van de app voeg je eerst dr homewizard toe als device. Er is geen settings pagina hiervoor die je bij andere apps soms hebt.

Verstuurd vanaf mijn iPhone

Op 30 mei 2019 om 21:44 heeft Abel <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Hallo Jeroen,

Vanavond heb ik de HomeWizard app gedeïnstalleerd en de beta geïnstalleerd. Daarna kon ik nergens meer het IP en de poort van de homewizard ingeven. Hierdoor ook geen apparaten meer selecteren. Nu heb ik de beta weer verwijderd en de originele weer geïnstalleerd maar heb ik hetzelfde.

Wat doe ik fout ?

Groet,
Ab

**Comment by jeroenbos22** [comment]
Ab,

Dat stel je in in app settings of op instellingen van het toegevoegde
homewizard apparaat (nu niet in de gelegenheid om na te kijken).

Het is aan te raden je homewizard een vast ip te geven.

Mvg

Jeroen


Op do 30 mei 2019 om 21:44 schreef Abel <notifications@github.com>

**Comment by Itsmmai** [comment]
Helaas staan er in de settings niets meer van de homewizard...

________________________________
Van: Jeroen <notifications@github.com>
Verzonden: Friday, May 31, 2019 12:13:04 PM
Aan: jeroenbos22/com.homewizard
CC: Ab Helversteijn-Smit; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Homewizard doet het niet meer na installatie beta (#35)

Ab,

Dat stel je in in app settings of op instellingen van het toegevoegde
homewizard apparaat (nu niet in de gelegenheid om na te kijken).

Het is aan te raden je homewizard een vast ip te geven.

Mvg

Jeroen


Op do 30 mei 2019 om 21:44 schreef Abel <notifications@github.com>

**Comment by jeroenbos22** [comment]
Ip adres van je homewizard kun je vinden in je router en in de instellingen
in je homewizard.

Poort is normaal gesproken 80.

Mvg

Jeroen

Op vr 31 mei 2019 om 18:28 schreef Abel <notifications@github.com>

**Comment by Itsmmai** [comment]
Dat weet ik maar ik kan het meer vinden op de homey

________________________________
Van: Jeroen <notifications@github.com>
Verzonden: Friday, May 31, 2019 7:14:57 PM
Aan: jeroenbos22/com.homewizard
CC: Ab Helversteijn-Smit; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Homewizard doet het niet meer na installatie beta (#35)

Ip adres van je homewizard kun je vinden in je router en in de instellingen
in je homewizard.

Poort is normaal gesproken 80.

Mvg

Jeroen

Op vr 31 mei 2019 om 18:28 schreef Abel <notifications@github.com>

**Comment by Itsmmai** [comment]
[Image]
[Image]
________________________________
Van: Ab Helversteijn-Smit <ab@helversteijn-smit.nl>
Verzonden: vrijdag, mei 31, 2019 7:49 PM
Aan: jeroenbos22/com.homewizard; jeroenbos22/com.homewizard
CC: Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Homewizard doet het niet meer na installatie beta (#35)

Dat weet ik maar ik kan het meer vinden op de homey

________________________________
Van: Jeroen <notifications@github.com>
Verzonden: Friday, May 31, 2019 7:14:57 PM
Aan: jeroenbos22/com.homewizard
CC: Ab Helversteijn-Smit; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Homewizard doet het niet meer na installatie beta (#35)

Ip adres van je homewizard kun je vinden in je router en in de instellingen
in je homewizard.

Poort is normaal gesproken 80.

Mvg

Jeroen

Op vr 31 mei 2019 om 18:28 schreef Abel <notifications@github.com>

**Comment by Itsmmai** [comment]
THANKS !!! Dat was het inderdaad.. Wat stom.. Helemaal overheen gekeken.

Nogmaals thanks,
Ab

Van: jtebbens <notifications@github.com>
Beantwoorden - Aan: "jeroenbos22/com.homewizard" <reply@reply.github.com>
Datum: vrijdag 31 mei 2019 om 10:28
Aan: "jeroenbos22/com.homewizard" <com.homewizard@noreply.github.com>
CC: Ab Helversteijn-Smit <ab@helversteijn-smit.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [jeroenbos22/com.homewizard] Homewizard doet het niet meer na installatie beta (#35)

Hallo Abel,

Na de installatie van de app voeg je eerst dr homewizard toe als device. Er is geen settings pagina hiervoor die je bij andere apps soms hebt.

Verstuurd vanaf mijn iPhone

Op 30 mei 2019 om 21:44 heeft Abel <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Hallo Jeroen,

Vanavond heb ik de HomeWizard app gedeïnstalleerd en de beta geïnstalleerd. Daarna kon ik nergens meer het IP en de poort van de homewizard ingeven. Hierdoor ook geen apparaten meer selecteren. Nu heb ik de beta weer verwijderd en de originele weer geïnstalleerd maar heb ik hetzelfde.

Wat doe ik fout ?

Groet,
Ab
