### ISSUE TITLE
Homey homewizard update niet

### ISSUE THREAD

**Issue by Itsmmai** [jeroenbos22/com.homewizard#36]
Heren,

Er gaat was mis. De temperatuur en regen  sensoren in mijn homewizard geven de stand van 9 dagen geleden aan. Kan ik hier iets aan doen?

Groet,
Abel

**Comment by RB-Dibbes** [comment]
LS,

Ik ervaar het zelfde probleem bij mijn temperatuur sensoren. Opnieuw installeren van de sensoren verhelpt het probleem voor 1-2 dagen, waarna de temperatuur lijkt te bevriezen en niet meer overeenkomst met de werkelijke temperatuur. Is hier een oplossing voor?

Groet,

René

**Comment by Farcorner** [comment]
Ik heb sinds kort hetzelfde probleem. 
Gaat bij mij om een 3 temperatuur sensoren en een EnergyLink. 

Toevoegen in Homey gaat zonder probleem maar na 1 á 2 dagen wordt er geen nieuwe data meer opgehaald vanuit de HomeWizard. 

Groet,

Frans

**Comment by jtebbens** [comment]
Hoi ik ervaar deze problemen totaal niet. Homey firmware 2.4.1 en gaat al maanden prima. Energylink en temperatuur sensoren. Kunnen jullie nakijken of Homewizard een vast ip heeft en niet een DHCP adres die wisselt? Krijg je met de gegevens wel een reactie op /get-sensors als je dit in een webbrowser zoekt? HTTP://x.x.x.x/<wachtwoord>/get-sensors

**Comment by Farcorner** [comment]
HomeWizard heeft een vast IP-adres. Ook na de succesvolle installatie niets aangepast in de app. 

Sensoren zijn via de HomeWizard app wel te lezen en worden daar regelmatig ge-update. 

Als ik surf naar HTTP://ip.homewizard/get-sensors krijg ik het volgend: {"status": "failed", "error": 1, "version": "3.403", "request": {"route": "" }}

**Comment by jtebbens** [comment]
Je moet wachtwoord na de / van je ip.
Ok vast ip dus. Kan je bij de volgende keer dat je merkt dat update niet gebeurt de Homewizard app herstarten op de Homey.
Gaarne nog firmware vermelden van Homey want ik vermoed dat er een relatie is met de GB van Homey firmware sinds 2.5.x

**Comment by Farcorner** [comment]
Zojuist opnieuw ingelogd op de HomeWizard en dit maal wel de data ontvangen: {"status": "ok", "version": "3.403", "request": {"route": "/get-sensors" }, "response": {"preset":0,"time":"2019-08-06 09:17","switches":[],"uvmeters":[],"windmeters":[],"rainmeters":[],"thermometers":[{"id":0,"name":"Koelkast","code":"4875181","model":1,"lowBattery":"no","version":2.31,"te":6.6,"hu":70,"te+":8.5,"te+t":"01:57","te-":1.5,"te-t":"03:01","hu+":79,"hu+t":"01:14","hu-":55,"hu-t":"02:53","outside":"yes","favorite":"no"},{"id":1,"name":"Vriezer","code":"2021370","model":1,"lowBattery":"no","version":2.31,"te":-22.2,"hu":54,"te+":-22.2,"te+t":"00:05","te-":-22.3,"te-t":"00:00","hu+":55,"hu+t":"00:00","hu-":54,"hu-t":"01:39","outside":"no","favorite":"no"},{"id":2,"name":"Patchkast","channel":3,"model":0,"te":28.0,"hu":46,"te+":28.4,"te+t":"00:00","te-":28.0,"te-t":"08:25","hu+":47,"hu+t":"00:00","hu-":45,"hu-t":"01:29","outside":"no","favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [{"id":0,"favorite":"no","name":"EnergyLink","code":"149457","t1":"none","c1":0,"t2":"none","c2":0,"tariff":2,"s1":null,"s2":null,"aggregate":{"po":-66,"dayTotal":3.84,"po+":2469,"po+t":"01:04","po-":-854,"po-t":"09:12"},"used":{"po":0,"dayTotal":3.90,"po+":2469,"po+t":"01:04","po-":0,"po-t":"09:06"},"gas":{"lastHour":0.00,"dayTotal":0.39},"kwhindex":0.00,"wp":0}], "heatlinks": [], "hues": [], "scenes": [], "kakusensors": [], "cameras": []}}

**Comment by Farcorner** [comment]
Verdere gegevens zijn als volgt: 
Homey versie: 2.5.0
App versie: 2.8.0.383

Ik heb het geprobeerd met de stable en beta versie en heb met beide hetzelfde probleem. Opnieuw opstarten van de HomeWizard, de Homey of de app op de Homey hebben tot nu toe geen effect gehad.

**Comment by jtebbens** [comment]
Je schrijft dat je sinds kort dit probleem merkt. Begrijp ik goed dat het wel eerder goed gewerkt heeft? Zo ja vanaf wanneer is het probleem begonnen? Vanaf firmware upgrade van Homey? Ik zelf heb met 2.4.1 geen probleem en jij zit nu op 2.5.0 vandaar de vraag. Anders moeten we Athom melding maken.

**Comment by Farcorner** [comment]
Het heeft goed gewerkt maar sinds wanneer het probleem precies voorkomt durf ik niet te zeggen. 
De update naar 2.5.0 is van een aantal weken geleden (er is dus de mogelijkheid dat het probleem samen hangt de update).

**Comment by Farcorner** [comment]
Gisteren update gedaan naar 2.5.1. Hierna de onderdelen van de HomeWizard opnieuw toegevoegd in de Homey hiermee lijkt het probleem opgelost te zijn. (Nu 13 uur stabiel)

**Comment by jtebbens** [comment]
Ok bedankt voor je reactie en update. Lijkt dus blijkbaar op firmware van Homey dan.
