### ISSUE TITLE
Homewizard app thermometers

### ISSUE THREAD

**Issue by WoutBkk** [jeroenbos22/com.homewizard#37]
De thermometers van de homewizard hebben soms een vertraging van 6 uur voordat deze een update krijgen in de Homey.
Dit is erg lastig als je een schakeling op temperatuur wilt maken, een flow van rolluiken omlaag als de temperatuur in de tuin 21,5 graden is (zonkant) dan werkt dat natuurlijk niet als de uitlezing van de temperatuur 6 uur achter loopt.
Deze flow heb ik dus weer gestopt en ben met de schakeling terug gegaan naar de homewizard die de temperatuur wel beter en sneller uitleest, dus een overstap naar de Homey is teruggezet.
Kan dit op de een of andere wijze aangepast worden dat het wel gaat werken, temperatuur minimaal 6x per uur uitlezen of meer.
W.B.

**Comment by Farcorner** [comment]
Hi Wout, 

Ik had een zelfde soort probleem met de temperatuur sensoren. 

Nadat ik Homey de update naar 2.5.1 heb gegeven + het opnieuw toevoegen van de sensoren heb ik zelf geen problemen meer ondervonden. Misschien dat dit voor jouw ook de oplossing kan zijn.

**Comment by WoutBkk** [comment]
Kan ik hier uit opmaken dat er niets aan gedaan zal worden of niets aan te doen is?
Als antwoord heb ik dit gekregen; Closed #37.

**Comment by jeroenbos22** [comment]
Wout,

Ik had uit de reactie van Farcorner opgemaakt dat er momenteel geen probleem is aangezien het bij hem werkt na firmware update. Had je zijn oplossing geprobeerd?

**Comment by WoutBkk** [comment]
Jeroen,

Mijn thermometers worden door de homewizard prima uitgelezen maar via de app in homey lopen ze iets op achter een uur of zes soms vier uur.
Dus mijn rolluiken aan de tuinkant op. Uitentemperatuur schakelen in een flow van de homey is dan waardeloos.
De schakeling weer teruggezet in de taken van de homewizard, reactie van Farcorner wel uitgeprobeerd en dat werkt niet, ook niet bij een vriend van mij welke ook rolluiken een thermometer en een homewizard en homey heeft.
Tevens gaf ik Falcorner ook al aan dat de homewizard app geheel losstaat van de homey update en ik denk dat jij als maker en ontwikkelaar van de homewizard app dat ook weet.
En de homewizard kan gewoon niet weg vanwege veel andere schakelingen die ik zonder de homewizard app niet in de homey zou hebben.

 Met vriendelijke groet,

Wout Bakker

Verstuurd vanaf mijn iPad

**Comment by jtebbens** [comment]
Hoi Wouter,

Ik begrijp je frustratie maar onze Homewizard app die op Homey draait kan last hebben van de firmware van Homey zelf. We maken gebruik van de connectie / communicatie laag van Homey en dus hier van afhankelijk (lees firmware core updates beinvloeden dit). Ik heb zelf thuis nog Homey firmware 2.4.1 draaien en heb totaal geen problemen met mijn Homewizard en Energylink. Alle temperatuur sensoren werken naar behoren en krijgen iedere update van temperatuur (mits de temperaruur is veranderd). Kan het eventueel zijn dat een temperatuur op Homewizard zelf ook stabiel een bepaalde waarde heeft (ook als het recent geupdate is). Homey zal tonen dat de waarde onveranderd is voor bijvoorbeeld 1 uur.

Ik heb meegelezen in de probleemstelling tijdens mijn vakantie en zal eens kijken of ik met de meest recente firmware van Homey wat kan testen. Zoals gezegd net terug maar zal even wat zaken moeten oppakken. Ik vermoed dat er iets mis was met 2.5.0 en dit lijkt voor 2.5.1 opgelost te zijn. 

Kan je je huidige firmware van Homey geven die je nu draait?
Verder kan je ook een testje doen gedurende 5 min met een ping vanaf een desktop naar Homewizard ip adres zelf en kijken of je een stabiel wifi verbinding hebt voor Homewizard zelf? Ook ikzelf heb last gehad met nieuwe wifi accespoints en de dramatische wifi chip van Homewizard zelf (spontaan wegvallen van Homewizard wifi verbinding). Dit staat los van de 433mhz of 868mhz signalen die je thermometers en andere sensoren sturen naar je Homewizard. Je kan dus prima nieuwe waarden op deze frequentie ontvangen maar als onze Homewizard app op Homey geen connectie kan maken via de Homewizard wifi verbinding werkt het dus niet.
Ik wil nameljjk connectie problemen met Homey naar Homewizard uitsluiten aangezien we ongeveer iedere 10 a 20 seconden een pull doen vanuit onze App naar je Homewizard om deze uit te lezen. Als daar timeouts of errors tussen zitten dan krijg je inderdaad problemen van dergelijke aard.

Alvast bedankt.

Kind regards / Groet,
Jeroen

Op 9 aug. 2019 om 18:07 heeft WoutBkk <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

Jeroen,

Mijn thermometers worden door de homewizard prima uitgelezen maar via de app in homey lopen ze iets op achter een uur of zes soms vier uur.
Dus mijn rolluiken aan de tuinkant op. Uitentemperatuur schakelen in een flow van de homey is dan waardeloos.
De schakeling weer teruggezet in de taken van de homewizard, reactie van Farcorner wel uitgeprobeerd en dat werkt niet, ook niet bij een vriend van mij welke ook rolluiken een thermometer en een homewizard en homey heeft.
Tevens gaf ik Falcorner ook al aan dat de homewizard app geheel losstaat van de homey update en ik denk dat jij als maker en ontwikkelaar van de homewizard app dat ook weet.
En de homewizard kan gewoon niet weg vanwege veel andere schakelingen die ik zonder de homewizard app niet in de homey zou hebben.

 Met vriendelijke groet,

Wout Bakker

Verstuurd vanaf mijn iPad

**Comment by jtebbens** [comment]
Is het nog gelukt Wout?
