### ISSUE TITLE
Windmeter values are empty

### ISSUE THREAD

**Issue by EricMuhren** [jeroenbos22/com.homewizard#38]
Hi Jeroen, you did a good job! Everything si working fine, but the windmeter values stay empty. 

To obtain the windid I submit the following url:
http://192.168.2.100/xxxxx/wilist
which results in:
{"status": "ok", "version": "3.403", "request": {"route": "/wilist" }, "response": [{"id":2,"name":"Wind","model":0,"unit":0,"ws":0.6,"dir":"SE 135","gu":2.2,"wc":26.8,"te":26.8,"ws+":1.2,"ws+t":"15:18","ws-":0.0,"ws-t":"00:00","favorite":"no"}]}

In my case the windid = 2

To get the winddata I submit:
http://192.168.2.100/xxxxx/wi/graph/2/day then I get:

{"status": "ok", "version": "3.403", "request": {"route": "/wi" }, "response": [{"t":"2019-08-08 00:10","ws":1.6,"gu":2.5,"dir":157}, etc...

Perhaps you can fix my problem with this information.

Thanks

**Comment by jeroenbos22** [comment]
Eric,

Are you on the beta app? 0.2.1?

Gr Jeroen

**Comment by jeroenbos22** [comment]
@jtebbens Do we only take id 0 into account ATM?

**Comment by EricMuhren** [comment]
Hi Jeroen,

No I’m using version 0.2.0.

Verzonden vanuit Mail voor Windows 10

Van: Jeroen
Verzonden: vrijdag 9 augustus 2019 15:43
Aan: jeroenbos22/com.homewizard
CC: EricMuhren; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter values are empty (#38)

Eric,
Are you on the beta app? 0.2.1?
Gr Jeroen
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by EricMuhren** [comment]
Hi Jeroen,

Is the mail below meant for someone else perhaps?

Verzonden vanuit Mail voor Windows 10

Van: Jeroen
Verzonden: vrijdag 9 augustus 2019 15:44
Aan: jeroenbos22/com.homewizard
CC: EricMuhren; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter values are empty (#38)

@jtebbens Do we only take id 0 into account ATM?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by jeroenbos22** [comment]
Eric,

Please try 0.2.1, it can be installed through the appstore using the beta link. 0.2.1 has multiple fixes for the windmeter.

**Comment by EricMuhren** [comment]
OK, I didn’t know. I’ll install version 0.2.1 and let you know.

Verzonden vanuit Mail voor Windows 10

Van: Jeroen
Verzonden: vrijdag 9 augustus 2019 15:48
Aan: jeroenbos22/com.homewizard
CC: EricMuhren; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter values are empty (#38)

Eric,
Please try 0.2.1, it can be installed through the appstore using the beta link. 0.2.1 has multiple fixes for the windmeter.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by EricMuhren** [comment]
Hi Jeroen,

This was the solution. Now it works like a charm. Thank you!

Eric
Van: Jeroen
Verzonden: vrijdag 9 augustus 2019 15:48
Aan: jeroenbos22/com.homewizard
CC: EricMuhren; Author
Onderwerp: Re: [jeroenbos22/com.homewizard] Windmeter values are empty (#38)

Eric,
Please try 0.2.1, it can be installed through the appstore using the beta link. 0.2.1 has multiple fixes for the windmeter.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Deze e-mail is gecontroleerd op virussen door AVG.
http://www.avg.com

**Comment by jeroenbos22** [comment]
Eric,

Cool, then we're gonna promote that version stable. Thanks for trying

**Comment by EricMuhren** [comment]
Good idea Jeroen!
