### ISSUE TITLE
Implement Rainmeter value as trigger

### ISSUE THREAD

**Issue by EricMuhren** [jeroenbos22/com.homewizard#40]
Hi Jeroen,

Is it possible to implement the rainmeter value rain to implement as a Homey trigger. Something like "rain has changed". With that information it is possible to trigger the Somfy screens.

Eric

**Comment by jeroenbos22** [comment]
Eric,

Thanks for the idea. Not sure if you have it available as tag at the moment, if so you could use Homey logic to do the trick. Check if the tag has changed and trigger a flow on that.

**Comment by EricMuhren** [comment]
I don't think there's any logic available to implement this feature. You'll need an event to trigger the flow....or can you tell me how to implement "check if the tag has changed"?

**Comment by jtebbens** [comment]
I will add this to next version. There are 2 values from Homewizard Rainmeter. 3h and total. I will use the total value of the rainmeter.

**Comment by EricMuhren** [comment]
Hi Jeroen,

That would be great!

Thank you

Eric

**Comment by EricMuhren** [comment]
Hi,

Is there any progress at the moment? The raining season is starting :-)

Eric

**Comment by jtebbens** [comment]
Sorry got a private life as well that is asking attention. Bare with me.

**Comment by jtebbens** [comment]
Ok added flow trigger for rainfail....try this version if you like
https://github.com/jtebbens/com.homewizard/tree/beta

**Comment by jtebbens** [comment]
App also now available for testing in the beta channel

**Comment by EricMuhren** [comment]
Hi Jeroen, 

That's a quick fix. I've installed the beta version and changed my rain flow. Now...let it rain!

**Comment by jtebbens** [comment]
I dont own a rainmeter so hard for me to test so let me know.

**Comment by EricMuhren** [comment]
I'll let you know of course.

**Comment by jeroenbos22** [comment]
Repo has been changed to https://github.com/jtebbens/com.homewizard, please re-submit the issue there if still relevant.
